config/routes.rb
Rails.application.routes.draw do

  resources :users
  root 'welcome#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

    validates :name, :email, :age, presence: true
    validates :name, length: { minimum: 2, maximum: 50 }, format: { with: /\A[^0-9`!@#\$%\^&*+_=]+\z/, message: "Only allows letters" }
    validates :age, numericality: { only_integer: true }, length: { maximum: 3 }
    validates :email, uniqueness: true, on: :create, format: { with: URI::MailTo::EMAIL_REGEXP }, length: { maximum: 50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def application 
        
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :age)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ActionController::Base

    def index 
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.age %></td>
        <!--<td><%= link_to 'Show', user %></td>-->
        <!--<td><%= link_to 'Edit', edit_user_path(user) %></td>-->
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= sanitize @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= sanitize @user.email %>
</p>

<p>
  <strong>Age:</strong>
  <%= @user.age %>
</p>

<!--<%= link_to 'Edit', edit_user_path(@user) %> |-->
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<br>
<h1>Evaluación de pila de desarrollo Ruby on Rails</h1>
<h1>1-Autores:  Sudheer Kumar Bethapudi y Juan Manuel Rey Alvarez</h1>
<h1>2-Detalles de la pila:  En esta primera versión se usa Ruby on Rails y Sqlite3</h1>
<h1>3-Ejemplos:  En las próximas versiones se actualizará este punto a medida que se incorporen</h1>

<h1><%= link_to 'Acciones de seguridad realizadas en este ejemplo', users_path %></h1>
<!--<h1><%= link_to 'Prevención de inyección SQL', users_path %></h1>-->

<h1>4-Pasos para lanzar el contenedor:</h1> 

<h1>5-Se realizó una aplicación, con un poco más de complejidad para que se pudiera ver desplegada en otra nube, en este caso una especializada en aplicaciones desarrolladas en rails.</h1>

<h1>https://jm-sample-app.herokuapp.com/</h1>

<h1>En la misma se pusieron en práctica todas las medidas de protección que se prácticaron durante el desarrollo de las prácticas con la aplicación sencilla como se recomendó.
También se comprobó en la misma el uso de https y se verificó en las dos como se genera el token asociado
a los formularios y el de sesión</h1>

<h1>- En la carpeta donde se pongan todos los archivos se usa para desplegar la aplicación:</h1>
<h1> docker-compose up</h1>

<h1>- Puede ser necesario si realizas algún cambio en los archivo Gemfile o de Docker hacerlo de la siguiente forma:</h1>
<h1>docker-compose build</h1>
<h1>docker-compose up </h1>

<h1> Nota importante: Se busco como establecer las configuraciones globales y poder desactivarlas para páginas
especificas para poder crear dos entorno, uno con todo correcto y el otro incorrecto y no se encontró, 
es decir si se activa es para todos o sino se tiene que desactivar, aunque se considera que es muy productiva la
forma en que rails protege y ayuda al programador, este punto se considera un problema, ya que restringe un poco al
mismo programador.</h1>

app/views/welcome/otro.html.erb
<h1>Hello, Juan!</h1>